  const popularCompanies = [
    { symbol: "EFERT", name: "Engro Fertilizers" },
    { symbol: "ENGROH", name: "Engro Holdings" },
    { symbol: "FFC", name: "Fauji Fertilizer" },
    { symbol: "LUCK", name: "Lucky Cement" },
    { symbol: "HBL", name: "Habib Bank" },
    { symbol: "UBL", name: "United Bank" },
    { symbol: "MCB", name: "MCB Bank" },
    { symbol: "MEBL", name: "Meezan Bank" },
    { symbol: "OGDC", name: "Oil & Gas Development" },
    { symbol: "PPL", name: "Pakistan Petroleum" },
    { symbol: "MARI", name: "Mari Energies" },
    { symbol: "HUBC", name: "Hub Power" },
    { symbol: "SYS", name: "Systems Limited" },
    { symbol: "PSO", name: "Pakistan State Oil" },
  ];